@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoic3R1ZGVudEBhZ2guZWR1LnBsIiwiaWF0IjoxNzY3NzkxNzk3LCJleHAiOjE3Njc3OTUzOTd9.LCVeRHg_WIBoIKjO6GGEpVTIocKMEe1HkP9Rn8VvehU


####################################
# SERWIS 3: REJESTRACJA (Port 3003)
####################################
POST http://localhost:3003/api/register
Content-Type: application/json

{
    "email": "student@agh.edu.pl",
    "password": "mojehaslo"
}

###

####################################
# SERWIS 3: LOGOWANIE (Port 3003)
####################################
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "email": "student@agh.edu.pl",
    "password": "mojehaslo"
}

###

####################################
# SERWIS 1: DODAJ KSIĄŻKĘ (Port 3001)
####################################
POST http://localhost:3001/api/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Wojna makowa",
    "author": "George R. R. Martin",
    "year": 2023
}

###

####################################
# SERWIS 2: ZŁOENIE ZAMÓWIENIA (Port 3002)
####################################
POST http://localhost:3002/api/orders
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": 1, 
    "bookId": 3,
    "quantity": 2
}

###

####################################
# SERWIS 2: ZMIANA ILOŚCI W ZAMÓWIENIU (Port 3002)
####################################
PATCH http://localhost:3002/api/orders/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "quantity": 10
}


#######################################
# PRÓBA DODANIA KSIĄKI BEZ TOKENA (BŁĄD 401)
#######################################
POST http://localhost:3001/api/books
Content-Type: application/json

{
    "title": "Niezgodna",
    "author": "Veronica Roth",
    "year": 2011
}
###